name: My First GitHub Action

on: [push]

jobs:
  build-app:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Sets the vercel env
        run: |
         cd build 
         mkdir .vercel
         cd .vercel
         touch project.json
          echo '{ "projectId": "your-project-id", "orgId": "your-org-id" }' > .vercel/project.json
      - name: Deploy to Vercel
        run: yarn deploy
      - name: Setup finish
        run: echo "hurray!"
        
